
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/productdb?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  #??swagger 3?Spring boot???????
  jackson:
    # ?? java.util.Date, Calendar ???????????
    date-format: yyyy-MM-dd HH:mm:ss
    # ????
    locale: zh
    # ??????
    time-zone: GMT+8
    # ??????@JsonInclude????????????NON_NULL ?????????????,??????JsonInclude.Include
    # default-property-inclusion: NON_NULL
    serialization:
      # ??? java.util.Date, Calendar ??????(???)
      WRITE_DATES_AS_TIMESTAMPS: false
      # ???????? null??????
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      # ??????json ??? pojo ????????????
      FAIL_ON_UNKNOWN_PROPERTIES: false


# ??mp???????????
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl