spring:
  security:
    user:
      name: root
      password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    repositories:
      base-package: demo.dao.UserRepository

  datasource:
    url: jdbc:mysql://localhost:3306/productdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root







